<?php

/**
 * @file
 * Provides primary Drupal hook implementations.
 *
 * Adds a JavaScript snippet to selected page responses to trigger analytics and
 * other tracking items configured using the Google Tag Manager.
 */

/**
 * Default for matching all items except listed.
 */
const GOOGLE_TAG_EXCLUDE_LISTED = 'exclude listed';

/**
 * Default for matching only listed items.
 */
const GOOGLE_TAG_INCLUDE_LISTED = 'include listed';

/**
 * Default list of relative paths.
 */
define('GOOGLE_TAG_PATHS', "admin*\nbatch*\nnode/add*\nnode/*/edit\nnode/*/delete\nuser/*/edit*\nuser/*/cancel*");

/**
 * Default list of HTTP response statuses that override path conditions.
 */
define('GOOGLE_TAG_STATUSES', "403 Forbidden\n404 Not Found");

/**
 * Default list of tag classes to allow.
 */
define('GOOGLE_TAG_WHITELIST_CLASSES', "google\nnonGooglePixels\nnonGoogleScripts\nnonGoogleIframes");

/**
 * Default list of tag classes to forbid.
 */
define('GOOGLE_TAG_BLACKLIST_CLASSES', "customScripts\ncustomPixels");

/**
 * Implements hook_config_info().
 */
function google_tag_config_info() {
  $prefixes['google_tag.settings'] = array(
    'label' => t('Google Tag Manager settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_menu().
 */
function google_tag_menu() {
  $items['admin/config/system/google_tag'] = array(
    'title' => 'Google Tag Manager',
    'description' => 'Configure the website integration with GTM and the resultant capturing of website analytics.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('google_tag_settings_form'),
    'access arguments' => array('administer google tag manager'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'google_tag.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function google_tag_permission() {
  return array(
    'administer google tag manager' => array(
      'title' => t('Administer Google Tag Manager'),
      'description' => t('Configure the website integration with Google Tag Manager.'),
      'restrict access' => TRUE,
      'warning' => t('Allows people to inject arbitrary JavaScript into the page using Google Tag Manager.'),
    ),
  );
}

/**
 * Implements hook_flush_caches().
 */
function google_tag_flush_caches() {
  google_tag_assets_create();
}

/**
 * Implements hook_preprocess_page().
 *
 * Adds the snippet to the page array if the insertion conditions are met.
 */
function google_tag_preprocess_page(&$variables) {
  if (!google_tag_insert_snippet()) {
    return;
  }

  // Call sequence:
  // - backdrop_render_page()
  //   - hook_preprocess_page()
  //   - hook_page_alter()
  //   - backdrop_render()
  // - backdrop_render()
  //   - callbacks in $elements['#theme_wrappers']
  //     - hook_preprocess_html(): 'html' is the wrapper for page
  //     - templates may add tags after body tag
  //   - callbacks in $elements['#post_render']
  //     - google_tag_page_process(): callback set here

  $base_path = 'public:/';
  $include_classes = config_get('google_tag.settings','google_tag_include_classes');

  $types = $include_classes ? array('data_layer', 'script') : array('script');

  $data_layer = config_get('google_tag.settings','google_tag_data_layer');
  if ($include_classes && module_exists('datalayer') && $data_layer == 'dataLayer') {
    $classes = config_get('google_tag.settings','google_tag_data_layer_classes');
    if ($classes) {
      // Add data_layer using dataLayer module.
      datalayer_add($classes);
    }
    $types = array('script');
  }

  // Add data_layer and script snippets to head (by default).
  $include_script_as_file = config_get('google_tag.settings','google_tag_include_file');
  if ($include_script_as_file == 1) {
    foreach ($types as $type) {
      // A stream wrapper may be passed as $data to backdrop_add_js($data) because
      // backdrop_get_js() calls file_create_url($data). The latter will work with
      // whichever class implements the stream, e.g. local, S3, or App Engine.
      $path = "$base_path/google_tag/google_tag.$type.js";
      // @todo Will it matter if file is empty?
      backdrop_add_js($path, array('group' => JS_LIBRARY * 2, 'requires_jquery' => FALSE, 'defer' => 'true'));
    }
  }
  else {
    foreach ($types as $type) {
      $url = "$base_path/google_tag/google_tag.$type.js";
      $contents = @file_get_contents($url);
      // @see backdrop_get_js()
      // For inline JavaScript to validate as XHTML, all JavaScript containing
      // XHTML needs to be wrapped in CDATA.
      if ($contents) {
        backdrop_add_js($contents, array('type' => 'inline', 'group' => JS_LIBRARY * 2, 'requires_jquery' => FALSE));
      }
    }
  }

  // Add noscript snippet to page_top region.
  $type = 'noscript';
  $url = "$base_path/google_tag/google_tag.$type.js";
  $noscript = @file_get_contents($url);

  if ($noscript) {
    // Note: for any theme that follows the pattern of core page.tpl.php in the
    // system module (e.g. bootstrap theme), this does not place the snippet
    // immediately after the body tag but rather after the 'skip-link' div.
    $google_tag = array(
      '#markup' => $noscript,
      '#weight' => -10,
    );
    // Since render arrays can't be passed to page.tpl.php (since it has no
    // preprocess laer -- it's an anomoly) we pre-render here.
    $variables['page_bottom'] .= backdrop_render($google_tag);
  }

}

/**
 * Determines whether to insert the snippet on the response.
 *
 * @return bool
 *   TRUE if the conditions are met; FALSE otherwise.
 */
function google_tag_insert_snippet() {
  $id = config_get('google_tag.settings','google_tag_container_id');

  if (empty($id)) {
    // No container ID.
    return FALSE;
  }
  $satisfied = TRUE;
  if (!_google_tag_status_check() || !_google_tag_path_check() || !_google_tag_role_check()) {
    // Omit snippet if any condition is not met.
    $satisfied = FALSE;
  }
  // Allow other modules to alter the insertion criteria.
  backdrop_alter('google_tag_insert', $satisfied);
  $debug = config_get('google_tag.settings','google_tag_debug_output');
  $debug ? backdrop_set_message(t('after alter @satisfied', array('@satisfied' => $satisfied))) : '';
  return $satisfied;
}

/**
 * Determines whether to insert the snippet based on status code settings.
 *
 * @return bool
 *   TRUE if the status conditions are met; FALSE otherwise.
 */
function _google_tag_status_check() {
  static $satisfied;

  if (!isset($satisfied)) {
    $debug = config_get('google_tag.settings','google_tag_debug_output');
    $toggle = config_get('google_tag.settings','google_tag_status_toggle');
    $statuses = config_get('google_tag.settings','google_tag_status_list');

    if (empty($statuses)) {
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED);
    }
    else {
      // Get the HTTP response status.
      $status = backdrop_get_http_header('status');
      $satisfied = $status && strpos($statuses, $status) !== FALSE;
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED) ? !$satisfied : $satisfied;
    }
    $debug ? backdrop_set_message(t('google_tag')) : '';
    $debug ? backdrop_set_message(t('status check @satisfied', array('@satisfied' => $satisfied))) : '';
  }
  return $satisfied;
}

/**
 * Determines whether to insert the snippet based on the path settings.
 *
 * @return bool
 *   TRUE if the path conditions are met; FALSE otherwise.
 */
function _google_tag_path_check() {
  static $satisfied;

  if (!isset($satisfied)) {
    $debug = config_get('google_tag.settings','google_tag_debug_output');
    $toggle = config_get('google_tag.settings','google_tag_path_toggle');
    $paths = config_get('google_tag.settings','google_tag_path_list');

    if (empty($paths)) {
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED);
    }
    else {
      // @todo Are not some paths case sensitive???
      // Convert the paths to lowercase before comparison.
      $paths = backdrop_strtolower($paths);
      $path = backdrop_strtolower(backdrop_get_path_alias($_GET['q']));
      $satisfied = backdrop_match_path($path, $paths);
      // @todo Lowercase $_GET['q'] before comparison? What is purpose of this check?
      if ($path != $_GET['q']) {
        $satisfied = $satisfied || backdrop_match_path($_GET['q'], $paths);
      }
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED) ? !$satisfied : $satisfied;
    }
    $debug ? backdrop_set_message(t('path check @satisfied', array('@satisfied' => $satisfied))) : '';
  }
  return $satisfied;
}

/**
 * Determines whether to insert the snippet based on the user role settings.
 *
 * @return bool
 *   TRUE if the role conditions are met; FALSE otherwise.
 */
function _google_tag_role_check() {
  global $user;
  static $satisfied;

  if (!isset($satisfied)) {
    $debug = config_get('google_tag.settings','google_tag_debug_output');
    $toggle = config_get('google_tag.settings','google_tag_role_toggle');
    $roles = config_get('google_tag.settings','google_tag_role_list');
    $roles = array_filter($roles);

    if (empty($roles)) {
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED);
    }
    else {
      $satisfied = FALSE;
      // Check user roles against listed roles.
      $satisfied = (bool) array_intersect($roles, $user->roles);
      $satisfied = ($toggle == GOOGLE_TAG_EXCLUDE_LISTED) ? !$satisfied : $satisfied;
    }
    $debug ? backdrop_set_message(t('role check @satisfied', array('@satisfied' => $satisfied))) : '';
  }
  return $satisfied;
}

/**
 * Saves snippet files and data layer classes based on current settings.
 */
function google_tag_assets_create() {
  module_load_include('inc', 'google_tag', 'google_tag.admin');
  _google_tag_assets_create();
}
